name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      run: |
        sudo apt update
        sudo apt install -y openjdk-8-jdk
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV

    - name: Install Android SDK and dependencies
      run: |
        sudo apt install -y wget unzip
        wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip -O sdk-tools.zip
        unzip sdk-tools.zip -d $HOME/android-sdk
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses
        yes | $HOME/android-sdk/tools/bin/sdkmanager --update
        yes | $HOME/android-sdk/tools/bin/sdkmanager "platforms;android-29" "build-tools;34.0.0" "extras;android;m2repository" "extras;google;m2repository" "platform-tools"

    - name: Check AIDL installation
      run: |
        if [ -f "$HOME/android-sdk/build-tools/34.0.0/aidl" ]; then
          echo "AIDL is installed."
        else
          echo "AIDL is not installed."
          exit 1
        fi

    - name: Install other dependencies
      run: |
        sudo apt install -y python3-pip build-essential git
        pip install --upgrade pip
        pip install cython buildozer requests

    - name: Build the APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: ./bin/android/debug/*.apk
